# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'if.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_if_form(object):
    def setupUi(self, if_form):
        if_form.setObjectName("if_form")
        if_form.resize(160, 75)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(if_form.sizePolicy().hasHeightForWidth())
        if_form.setSizePolicy(sizePolicy)
        if_form.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        if_form.setStyleSheet("QWidget {\n"
"  background-color: #2a1a41;\n"
"}\n"
"\n"
"QPushButton {\n"
"  border-radius: 4px;\n"
"  background-color: #8EDBCE;\n"
"  font-family: \'Montserrat\', sans-serif;\n"
"  color: black;\n"
"  transition: background-color 1000ms linear;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #CDF9EF;\n"
"}\n"
"\n"
"QLabel {\n"
"  color: #4bd1e8;\n"
"}\n"
"\n"
"QLineEdit{\n"
"  border-radius: 1px;\n"
"  background-color: #4bd1e8;\n"
"  border: 1px solid white;\n"
"}\n"
"\n"
"QComboBox {\n"
"  background-color: #4bd1e8;\n"
"  color: black;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"  background-color: #4bd1e8;\n"
"  color: black;\n"
"}\n"
"\n"
"")
        self.left_if_box = QtWidgets.QLineEdit(if_form)
        self.left_if_box.setGeometry(QtCore.QRect(10, 10, 51, 21))
        self.left_if_box.setObjectName("left_if_box")
        self.right_if_box = QtWidgets.QLineEdit(if_form)
        self.right_if_box.setGeometry(QtCore.QRect(100, 10, 51, 21))
        self.right_if_box.setObjectName("right_if_box")
        self.add_if_btn = QtWidgets.QPushButton(if_form)
        self.add_if_btn.setGeometry(QtCore.QRect(10, 40, 141, 25))
        self.add_if_btn.setObjectName("add_if_btn")
        self.if_comboBox = QtWidgets.QComboBox(if_form)
        self.if_comboBox.setGeometry(QtCore.QRect(60, 10, 41, 21))
        self.if_comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.if_comboBox.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.if_comboBox.setObjectName("if_comboBox")
        self.if_comboBox.addItem("")
        self.if_comboBox.addItem("")

        self.retranslateUi(if_form)
        QtCore.QMetaObject.connectSlotsByName(if_form)

    def retranslateUi(self, if_form):
        _translate = QtCore.QCoreApplication.translate
        if_form.setWindowTitle(_translate("if_form", "If settings"))
        self.add_if_btn.setText(_translate("if_form", "ADD If"))
        self.if_comboBox.setItemText(0, _translate("if_form", "=="))
        self.if_comboBox.setItemText(1, _translate("if_form", "<"))
