# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'input.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_input_form(object):
    def setupUi(self, input_form):
        input_form.setObjectName("input_form")
        input_form.resize(150, 75)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(input_form.sizePolicy().hasHeightForWidth())
        input_form.setSizePolicy(sizePolicy)
        input_form.setStyleSheet("QWidget {\n"
"  background-color: #2a1a41;\n"
"}\n"
"\n"
"QPushButton {\n"
"  border-radius: 4px;\n"
"  background-color: #8EDBCE;\n"
"  font-family: \'Montserrat\', sans-serif;\n"
"  color: black;\n"
"  transition: background-color 1000ms linear;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #CDF9EF;\n"
"}\n"
"\n"
"QLabel {\n"
"  color: #4bd1e8;\n"
"}\n"
"\n"
"QLineEdit {\n"
"  border-radius: 1px;\n"
"  border: 1px solid white;\n"
"  background-color: #4bd1e8\n"
"}\n"
"")
        self.right_input_box = QtWidgets.QLineEdit(input_form)
        self.right_input_box.setGeometry(QtCore.QRect(90, 10, 50, 20))
        self.right_input_box.setObjectName("right_input_box")
        self.add_input_btn = QtWidgets.QPushButton(input_form)
        self.add_input_btn.setGeometry(QtCore.QRect(10, 40, 130, 25))
        self.add_input_btn.setObjectName("add_input_btn")
        self.input_label = QtWidgets.QLabel(input_form)
        self.input_label.setGeometry(QtCore.QRect(10, 10, 71, 21))
        self.input_label.setObjectName("input_label")

        self.retranslateUi(input_form)
        QtCore.QMetaObject.connectSlotsByName(input_form)

    def retranslateUi(self, input_form):
        _translate = QtCore.QCoreApplication.translate
        input_form.setWindowTitle(_translate("input_form", "Input settings"))
        self.add_input_btn.setText(_translate("input_form", "ADD Input"))
        self.input_label.setText(_translate("input_form", "Variable name"))

