# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from interface import assign, if_, input, print, test_results
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QPushButton, QVBoxLayout, QWidget


class Ui_MainWindow(object):
    def __init__(self):
        super().__init__()
        #thread = {"id": "", "operations": []}
        threads = []

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(490, 192)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(490, 192))
        MainWindow.setMaximumSize(QtCore.QSize(490, 192))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet("QWidget {\n"
                                 "  background-color: #2a1a41;\n"
                                 "  font-family: \'Montserrat\', sans-serif;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton {\n"
                                 "  border-radius: 4px;\n"
                                 "  background-color: #8EDBCE;\n"
                                 "  color: black;\n"
                                 "  transition: background-color 1000ms linear;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:hover {\n"
                                 "  background-color: #CDF9EF;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton#del_thread_btn:hover, QPushButton#del_block_btn:hover {\n"
                                 "  background-color: #F08583;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton#add_thread_btn:hover, QPushButton#add_block_btn:hover {\n"
                                 "  background-color: #67F09D;\n"
                                 "}\n"
                                 "\n"
                                 "QLabel {\n"
                                 "  color: #4bd1e8;\n"
                                 "}\n"
                                 "\n"
                                 "QComboBox {\n"
                                 "  background-color: #4bd1e8\n"
                                 "}\n"
                                 "\n"
                                 "QComboBox QAbstractItemView{\n"
                                 "  background-color: #4bd1e8\n"
                                 "}\n"
                                 "\n"
                                 "\n"
                                 "QListWidget {\n"
                                 "  border-radius: 4px;\n"
                                 "  background-color: #4bd1e8\n"
                                 "}\n"
                                 "\n"
                                 "\n"
                                 "")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.add_thread_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_thread_btn.setGeometry(QtCore.QRect(120, 10, 81, 23))
        self.add_thread_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_thread_btn.setObjectName("add_thread_btn")
        self.add_thread_btn.clicked.connect(self.add_thread_event)
        self.del_thread_btn = QtWidgets.QPushButton(self.centralwidget)
        self.del_thread_btn.setGeometry(QtCore.QRect(210, 10, 81, 23))
        self.del_thread_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.del_thread_btn.setObjectName("del_thread_btn")
        self.add_block_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_block_btn.setGeometry(QtCore.QRect(310, 10, 81, 23))
        self.add_block_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_block_btn.setObjectName("add_block_btn")
        self.del_block_btn = QtWidgets.QPushButton(self.centralwidget)
        self.del_block_btn.setGeometry(QtCore.QRect(400, 10, 81, 23))
        self.del_block_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.del_block_btn.setObjectName("del_block_btn")
        self.gen_code_btn = QtWidgets.QPushButton(self.centralwidget)
        self.gen_code_btn.setGeometry(QtCore.QRect(10, 40, 101, 21))
        self.gen_code_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.gen_code_btn.setObjectName("gen_code_btn")
        self.test_threads_btn = QtWidgets.QPushButton(self.centralwidget)
        self.test_threads_btn.setGeometry(QtCore.QRect(10, 70, 101, 23))
        self.test_threads_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.test_threads_btn.setObjectName("test_threads_btn")
        self.save_threads_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_threads_btn.setGeometry(QtCore.QRect(10, 100, 101, 23))
        self.save_threads_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.save_threads_btn.setObjectName("save_threads_btn")
        self.load_threads_btn = QtWidgets.QPushButton(self.centralwidget)
        self.load_threads_btn.setGeometry(QtCore.QRect(10, 130, 101, 23))
        self.load_threads_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.load_threads_btn.setObjectName("load_threads_btn")
        self.clear_threads_btn = QtWidgets.QPushButton(self.centralwidget)
        self.clear_threads_btn.setGeometry(QtCore.QRect(10, 160, 101, 23))
        self.clear_threads_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.clear_threads_btn.setObjectName("clear_threads_btn")
        self.block_label = QtWidgets.QLabel(self.centralwidget)
        self.block_label.setEnabled(False)
        self.block_label.setGeometry(QtCore.QRect(310, 40, 81, 20))
        self.block_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.block_label.setStyleSheet("")
        self.block_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.block_label.setLineWidth(1)
        self.block_label.setAlignment(QtCore.Qt.AlignCenter)
        self.block_label.setObjectName("block_label")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setEnabled(False)
        self.logo.setGeometry(QtCore.QRect(10, 10, 101, 20))
        self.logo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.logo.setStyleSheet("")
        self.logo.setFrameShadow(QtWidgets.QFrame.Plain)
        self.logo.setLineWidth(1)
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setObjectName("logo")
        self.thread_list = QtWidgets.QListWidget(self.centralwidget)
        self.thread_list.setGeometry(QtCore.QRect(120, 40, 171, 143))
        self.thread_list.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.thread_list.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.thread_list.setObjectName("thread_list")
        item = QtWidgets.QListWidgetItem()
        self.thread_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.thread_list.addItem(item)
        self.block_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.block_comboBox.setGeometry(QtCore.QRect(400, 40, 81, 22))
        self.block_comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.block_comboBox.setObjectName("block_comboBox")
        self.block_comboBox.addItem("")
        self.block_comboBox.addItem("")
        self.block_comboBox.addItem("")
        self.block_comboBox.addItem("")
        self.block_comboBox.addItem("")
        self.blocks_list = QtWidgets.QListWidget(self.centralwidget)
        self.blocks_list.setGeometry(QtCore.QRect(310, 70, 171, 113))
        self.blocks_list.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.blocks_list.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.blocks_list.setObjectName("blocks_list")
        item = QtWidgets.QListWidgetItem()
        self.blocks_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.blocks_list.addItem(item)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Scheme Builder"))
        self.del_block_btn.setText(_translate("MainWindow", "DEL BLOCK"))
        self.block_label.setText(_translate("MainWindow", "Block type"))
        self.gen_code_btn.setText(_translate("MainWindow", "GENERATE CODE"))
        self.logo.setText(_translate("MainWindow", "Scheme Builder"))
        self.save_threads_btn.setText(_translate("MainWindow", "SAVE THREADS"))
        self.test_threads_btn.setText(_translate("MainWindow", "TEST THREADS"))
        self.add_thread_btn.setText(_translate("MainWindow", "ADD THREAD"))
        __sortingEnabled = self.thread_list.isSortingEnabled()
        self.thread_list.setSortingEnabled(False)
        item = self.thread_list.item(0)
        item.setText(_translate("MainWindow", "Thread 1"))
        item = self.thread_list.item(1)
        item.setText(_translate("MainWindow", "Thread 2"))
        self.thread_list.setSortingEnabled(__sortingEnabled)
        self.clear_threads_btn.setText(_translate("MainWindow", "CLEAR THREADS"))
        self.add_block_btn.setText(_translate("MainWindow", "ADD BLOCK"))
        self.block_comboBox.setItemText(0, _translate("MainWindow", "Assign"))
        self.block_comboBox.setItemText(1, _translate("MainWindow", "Print"))
        self.block_comboBox.setItemText(2, _translate("MainWindow", "Input"))
        self.block_comboBox.setItemText(3, _translate("MainWindow", "If"))
        self.block_comboBox.setItemText(4, _translate("MainWindow", "end if"))
        self.del_thread_btn.setText(_translate("MainWindow", "DEL THREAD"))
        __sortingEnabled = self.blocks_list.isSortingEnabled()
        self.blocks_list.setSortingEnabled(False)
        item = self.blocks_list.item(0)
        item.setText(_translate("MainWindow", "Elem1"))
        item = self.blocks_list.item(1)
        item.setText(_translate("MainWindow", "Elem2"))
        self.blocks_list.setSortingEnabled(__sortingEnabled)
        self.load_threads_btn.setText(_translate("MainWindow", "LOAD THREADS"))

    def implement_secondary_windows(self):
        self.assign_form = QtWidgets.QWidget()
        self.assign_ui = assign.Ui_assign_form()
        self.assign_ui.setupUi(self.assign_form)

        self.if_form = QtWidgets.QWidget()
        self.if_ui = if_.Ui_if_form()
        self.if_ui.setupUi(self.if_form)

        self.input_form = QtWidgets.QWidget()
        self.input_ui = input.Ui_input_form()
        self.input_ui.setupUi(self.input_form)

        self.print_form = QtWidgets.QWidget()
        self.print_ui = print.Ui_print_form()
        self.print_ui.setupUi(self.print_form)

        self.test_results_form = QtWidgets.QWidget()
        self.test_results_ui = test_results.Ui_test_results_form()
        self.test_results_ui.setupUi(self.test_results_form)

    def add_thread_event(self):
        self.assign_form.show()
