# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'print.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_print_form(object):
    def setupUi(self, print_form):
        print_form.setObjectName("print_form")
        print_form.resize(150, 75)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(print_form.sizePolicy().hasHeightForWidth())
        print_form.setSizePolicy(sizePolicy)
        print_form.setStyleSheet("QWidget {\n"
"  background-color: #2a1a41;\n"
"}\n"
"\n"
"QPushButton {\n"
"  border-radius: 4px;\n"
"  background-color: #8EDBCE;\n"
"  font-family: \'Montserrat\', sans-serif;\n"
"  color: black;\n"
"  transition: background-color 1000ms linear;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #CDF9EF;\n"
"}\n"
"\n"
"QLabel {\n"
"  color: #4bd1e8;\n"
"}\n"
"\n"
"QLineEdit {\n"
"  border-radius: 1px;\n"
"  border: 1px solid white;\n"
"  background-color: #4bd1e8\n"
"}\n"
"")
        self.print_box = QtWidgets.QLineEdit(print_form)
        self.print_box.setGeometry(QtCore.QRect(90, 10, 50, 20))
        self.print_box.setObjectName("print_box")
        self.add_print_btn = QtWidgets.QPushButton(print_form)
        self.add_print_btn.setGeometry(QtCore.QRect(10, 40, 130, 25))
        self.add_print_btn.setObjectName("add_print_btn")
        self.print_label = QtWidgets.QLabel(print_form)
        self.print_label.setGeometry(QtCore.QRect(10, 10, 71, 21))
        self.print_label.setObjectName("print_label")

        self.retranslateUi(print_form)
        QtCore.QMetaObject.connectSlotsByName(print_form)

    def retranslateUi(self, print_form):
        _translate = QtCore.QCoreApplication.translate
        print_form.setWindowTitle(_translate("print_form", "Print settings"))
        self.add_print_btn.setText(_translate("print_form", "ADD Print"))
        self.print_label.setText(_translate("print_form", "Variable name"))
